fix: Skip k3s component in zarf init for k3d clusters
The zarf init was incorrectly using --components=k3s which tries to
install k3s on the host (requires root). Since k3d already provides
a Kubernetes cluster, we should skip k3s and only install the required
Zarf infrastructure components.

Fixes the GitHub Actions CI failure:
ERROR: unable to deploy component "k3s": permission denied copying
k3s.service to /etc/systemd/system/